# 作業目標:
    了解 Convolution 卷積的組成

# 作業重點:
    修改 a_slice_prev, 檢查 Z 的輸出

In [0]:
import numpy as np

In [0]:
# GRADED FUNCTION: conv_single_step
def conv_single_step(a_slice_prev, W, b):
    """
    定義一層 Kernel (內核), 使用的參數說明如下
    Arguments:
        a_slice_prev -- 輸入資料的維度
        W -- 權重, 被使用在 a_slice_prev
        b -- 偏差參數 
    Returns:
        Z -- 滑動窗口（W，b）卷積在前一個 feature map 上的結果
    """

    # 定義一個元素介於 a_slice and W
    s = a_slice_prev * W
    # 加總所有的 "s" 並指定給Z.
    Z = np.sum(s)
    # Add bias b to Z. 這是 float() 函數,
    Z = float(Z + b)

    return Z

In [15]:
'''

np.random.seed(1)
#定義一個 axaxd 的 feature map
a_slice_prev = 
W = 
b = np.random.randn(1, 1, 1)

#取得計算後,卷積矩陣的值
Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)
'''

np.random.seed(1)
#定義一個 4x4x3 的 feature map
a_slice_prev = np.random.randn(1,2,3) #4個4*3
W = np.random.randn(1,2, 3)
b = np.random.randn(1, 1, 1)

#取得計算後,卷績矩陣的值
Z = conv_single_step(a_slice_prev, W, b)
print("Z =", Z)

Z = 9.083304976713565


In [19]:
a_slice_prev, W, b

(array([[[ 1.62434536, -0.61175641, -0.52817175],
         [-1.07296862,  0.86540763, -2.3015387 ]]]),
 array([[[ 1.74481176, -0.7612069 ,  0.3190391 ],
         [-0.24937038,  1.46210794, -2.06014071]]]),
 array([[[-0.3224172]]]))

In [20]:
np.sum(a_slice_prev* W)+ b

array([[[9.08330498]]])

### 測試整數

In [11]:
np.random.seed(1)
#定義一個 4x4x3 的 feature map
x = np.random.randint(10, size=48)
x 

array([5, 8, 9, 5, 0, 0, 1, 7, 6, 9, 2, 4, 5, 2, 4, 2, 4, 7, 7, 9, 1, 7,
       0, 6, 9, 9, 7, 6, 9, 1, 0, 1, 8, 8, 3, 9, 8, 7, 3, 6, 5, 1, 9, 3,
       4, 8, 1, 4])

In [30]:
x = np.reshape(x,(4,4,3))
x

array([[[5, 8, 9],
        [5, 0, 0],
        [1, 7, 6],
        [9, 2, 4]],

       [[5, 2, 4],
        [2, 4, 7],
        [7, 9, 1],
        [7, 0, 6]],

       [[9, 9, 7],
        [6, 9, 1],
        [0, 1, 8],
        [8, 3, 9]],

       [[8, 7, 3],
        [6, 5, 1],
        [9, 3, 4],
        [8, 1, 4]]])

In [0]:
np.random.seed(1)
#定義一個 4x4x3 的 feature map
w = np.random.randint(-1,1, size=48)
w = np.reshape(w,(4,4,3))

In [29]:
Z = conv_single_step(x, w, b)
print("Z =", Z)

Z = -100.3224172040135
